### PR TITLE
Updates in Allegro Ecal needed for Pandora

### PR DESCRIPTION
**Pull request by faltovaj**
BEGINRELEASENOTES

- Fix the segmentation type in CLD_o4_v05/LAr_ECalBarrel.xml
- Added material description per layer (interaction and radiation lengths) needed for Pandora in ECalBarrel_NobleLiquid_InclinedTrapezoids_o1_v03_geo.cpp and ECalBarrel_NobleLiquid_InclinedTrapezoids_o1_v04_geo.cpp

ENDRELEASENOTES

### CODE REVIEW

**Comment by faltovaj** [comment]
> Dear @faltovaj
> 
> Please keep the BEGIN/ENDRELEASENOTES lines.
> 
> Thanks

Sorry, fixed now.

**Comment by SwathiSasikumar** [comment]
The changes in ```LAr_ECalBarrel.xml``` and ```CalBarrel_NobleLiquid_InclinedTrapezoids_o1_v03_geo.cpp``` were already requested in PR https://github.com/key4hep/k4geo/pull/361. Maybe we close that one first? I will finalize the last request by Brieuc and finalize it.

**Comment by faltovaj** [comment]
> The changes in `LAr_ECalBarrel.xml` and `ECalBarrel_NobleLiquid_InclinedTrapezoids_o1_v03_geo.cpp` were already requested in PR #361. Maybe we close that one first? I will finalize the last request by Brieuc and update it.

I found another PR #382 implementing the change in `LAr_ECalBarrel.xml`. This should be closed as well ....

**Comment by BrieucF** [comment]
Handled by https://github.com/key4hep/k4geo/pull/361

**Pull request closed without merging**
