### PR TITLE
[FCCeeMDI] Use absolute path to import CAD files

### PR DESCRIPTION
**Pull request by BrieucF**
BEGINRELEASENOTES
- [FCCeeMDI] Use absolute path to import CAD files

ENDRELEASENOTES

It looks like, when importing CAD file with `<shape type="CAD_MultiVolume" ref="path_to_stl_file" unit="mm" material="LiquidNDecane">`, the path is relative to where the ddsim command is launched

### CODE REVIEW

**Comment by andresailer** [comment]
This should work https://github.com/AIDASoft/DD4hep/pull/1175  with recent enough DD4hep versions?

**Comment by BrieucF** [comment]
I have opened an issue in DD4hep (https://github.com/AIDASoft/DD4hep/issues/1313). Can we merge this regardless of the issue? I'd keep it like this even after the fix.

**Comment by andresailer** [comment]
I think this rather is an issue for key4hep-spack though. Because it comes down to ROOT with pcre2 (I think), which we have no control over in DD4hep.

**Comment by BrieucF** [comment]
I see. Does this prevent merging this PR?

**Comment by andresailer** [comment]
Apart from the full path making it harder to changing the files and trying things out with ones own copy of a folder. No, nothing prevents merging these changes.

**Comment by andresailer** [comment]
By the way

>It looks like, when importing CAD file with <shape type="CAD_MultiVolume" ref="path_to_stl_file" unit="mm" material="LiquidNDecane">, the path is relative to where the ddsim command is launched

Is this your interpretation of the TRegexp error mentioned in the DD4hep issue, or was this a different error message that caused the conclusion written here?

**Comment by BrieucF** [comment]
> Is this your interpretation of the TPRegexp error mentioned in the DD4hep issue, or was this a different error message that caused the conclusion written here?

No no, it comes from the fact that running `examples/DDCAD/compact/Check_Shape_RelativePath.xml` from the DD4hep directory does not work, while going to `examples/DDCAD/compact/` and running it from there works, as I tried to explain in https://github.com/AIDASoft/DD4hep/issues/1313. The mention of the TPRegexp error was just a side note that it is not easy to understand that the problem is "not finding the CAD file" based on the error message.

**Comment by andresailer** [comment]
It does not work in the way that there is the TPRegex error?

**Pull request merged**
