### PR TITLE
Fix printout issues in turbine endcap geometry; also add v02 of the geometry

### PR DESCRIPTION
**Pull request by varnes**
BEGINRELEASENOTES

* ECalEndcap_Turbine_o1_v01_geo: Fix issues with printout (to allow verbosity to be controlled from run script).  
* Add ECalEndcap_Turbine_o1_v01_geo of the "turbine" endcap geometry: which allows for more flexibility than v01 (for example, one can set different blade angles for the three wheels in v02).  As v02 is still a work in progress, the default xml points to v01.

ENDRELEASENOTES

### CODE REVIEW

**Comment by giovannimarchiori** [comment]
Hi @varnes,
what's the status of this PR? Do you still need to further modifications to v02 or is it ready to go?
Can you rebase and fix the conflicts so that the tests can be run?
Also, can you please add comments in the main xml to describe the CellID encoding bitfield?
Thanks a lot,
  Giovanni

**Comment by giovannimarchiori** [comment]
@BrieucF I would really like to merge soon this PR so that we can get rid of the tons of debug messages in regular output. Maybe we move ahead with this (after rebasing) and leave it to a future PR further developments on v02 (if any)?

**Comment by andresailer** [comment]
@varnes you need to rebase and fix conflicts

**Comment by BrieucF** [comment]
Hi Giovanni, yes, let's merge this asap. @varnes while you rebase and fix the conflicts, would you mind updating the relevant README with information about v02: https://github.com/key4hep/k4geo/tree/main/detector/calorimeter#ecalendcap_turbine, https://github.com/key4hep/k4geo/tree/main/FCCee/ALLEGRO/compact#allegro ?

**Comment by varnes** [comment]
Hi @BrieucF and @giovannimarchiori ,

  Sorry for being slow on this (some combination of a family event and the messages ending up in my spam folder contributed).  But I think it's ready now...

**Pull request merged**
